# fly.toml app configuration file generated for dengify on 2025-05-02T10:52:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dengify'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
